title: Just the Docs Template Test
description: Temporary, fur testing only
theme: just-the-docs

url: https://pdmosses.github.io/just-the-docs-template-test

aux_links:
  Test Repository: https://github.com/pdmosses/just-the-docs-template-test

plugins:
  - jekyll-default-layout
